Vagrant.configure("2") do |config|
	config.vm.box = "debian/jessie64"

	config.vm.network "forwarded_port", guest: 5432, host: 5432
	config.vm.network "forwarded_port", guest: 3306, host: 33306

	config.vm.synced_folder ".", "/vagrant", disabled: true
  
	config.vm.provider "virtualbox" do |vb|
		vb.memory = "256"
		vb.name = "gk-dev-vm"
	end 
  
	config.vm.provision "shell", inline: <<-SHELL
		echo "Updating system"

		sudo apt-get update
		sudo apt-get dist-upgrade -y

		echo "Installing Postgresql"

		sudo apt-get install -y postgresql-client-9.4 postgresql-9.4
		echo "Configuring and restarting PostgreSQL"
		echo 'listen_addresses = '"'"'*'"'" >> /etc/postgresql/9.4/main/postgresql.conf
		echo 'host    all             all             10.0.2.0/24            md5' >> /etc/postgresql/9.4/main/pg_hba.conf
		systemctl restart postgresql

		echo "Creating db with user"
		echo "CREATE ROLE gklients CREATEDB CREATEROLE CREATEUSER LOGIN UNENCRYPTED PASSWORD 'gklients'" | sudo -u postgres psql -a -f -
		echo "CREATE DATABASE gklients OWNER gklients" | sudo -u postgres psql -a -f -

		echo "Installing Mysql"
	
		sudo debconf-set-selections <<< 'mysql-server mysql-server/root_password password 123'
		sudo debconf-set-selections <<< 'mysql-server mysql-server/root_password_again password 123'

		sudo apt-get install -y mysql-server
		sudo sed -i "s/^bind-address/#bind-address/" /etc/mysql/my.cnf
		sudo service mysql restart

		sudo mysql -u root -p123 -e "DROP USER ''@'localhost';"
		sudo mysql -u root -p123 -e "DROP USER ''@'$(hostname)';"
		sudo mysql -u root -p123 -e "DROP DATABASE test;"
		sudo mysql -u root -p123 -e "GRANT ALL PRIVILEGES ON *.* TO 'root'@'%' IDENTIFIED BY '123' WITH GRANT OPTION; FLUSH PRIVILEGES; SET GLOBAL max_connect_errors=10000;"
		sudo service mysql restart

	SHELL
end
