alter table GKLIENTS_ONETIME_MAILING_CLIENT_LINK add constraint FK_GOMCL_ONETIME_MAILING foreign key (ONETIME_MAILING_ID) references GKLIENTS_ONETIME_MAILING(ID);
alter table GKLIENTS_ONETIME_MAILING_CLIENT_LINK add constraint FK_GOMCL_CLIENT foreign key (CLIENT_ID) references GKLIENTS_CLIENT(ID);
