alter table GKLIENTS_DISTRIBUTION add constraint FK_GKLIENTS_DISTRIBUTION_TEMPLATE foreign key (TEMPLATE_ID) references gklients_EMAIL_TEMPLATE(ID);
create index IDX_GKLIENTS_DISTRIBUTION_TEMPLATE on GKLIENTS_DISTRIBUTION (TEMPLATE_ID);
