alter table GKLIENTS_GK_NEWS_IMAGE add constraint FK_GKLIENTS_GK_NEWS_IMAGE_GK_NEWS foreign key (GK_NEWS_ID) references GKLIENTS_GK_NEWS(ID);
create index IDX_GKLIENTS_GK_NEWS_IMAGE_GK_NEWS on GKLIENTS_GK_NEWS_IMAGE (GK_NEWS_ID);
