alter table GKLIENTS_EMAIL_TEMPLATE_ATTACHMENT_LINK add constraint FK_GETAL_ATTACHMENT foreign key (ATTACHMENT_ID) references GKLIENTS_ATTACHMENT(ID);
alter table GKLIENTS_EMAIL_TEMPLATE_ATTACHMENT_LINK add constraint FK_GETAL_EMAIL_TEMPLATE foreign key (EMAIL_TEMPLATE_ID) references gklients_EMAIL_TEMPLATE(ID);
