alter table GKLIENTS_DISTRIBUTION_ATTACHMENT_LINK add constraint FK_GDAL_ATTACHMENT foreign key (ATTACHMENT_ID) references GKLIENTS_ATTACHMENT(ID);
alter table GKLIENTS_DISTRIBUTION_ATTACHMENT_LINK add constraint FK_GDAL_DISTRIBUTION foreign key (DISTRIBUTION_ID) references GKLIENTS_DISTRIBUTION(ID);
