-- begin gklients_MAGAZINE_ISSUE
alter table gklients_MAGAZINE_ISSUE add constraint FK_gklients_MAGAZINE_ISSUE_MAGAZINE_ID foreign key (MAGAZINE_ID) references gklients_MAGAZINE(ID)^
create index IDX_gklients_MAGAZINE_ISSUE_MAGAZINE on gklients_MAGAZINE_ISSUE (MAGAZINE_ID)^
-- end gklients_MAGAZINE_ISSUE
-- begin gklients_SCHEDULE
alter table gklients_SCHEDULE add constraint FK_gklients_SCHEDULE_MAGAZINE_ISSUE_ID foreign key (MAGAZINE_ISSUE_ID) references gklients_MAGAZINE_ISSUE(ID)^
-- end gklients_SCHEDULE
-- begin gklients_EMAIL_TEMPLATE
create unique index IDX_gklients_EMAIL_TEMPLATE_UNIQ_EMAIL_TYPE on gklients_EMAIL_TEMPLATE (EMAIL_TYPE) where DELETE_TS is null ^
-- end gklients_EMAIL_TEMPLATE

-- begin GKLIENTS_ELVER_SUBSCRIPTIONalter table GKLIENTS_ELVER_SUBSCRIPTION add constraint FK_GKLIENTS_ELVER_SUBSCRIPTION_CLIENT_ID foreign key (CLIENT_ID) references GKLIENTS_CLIENT(ID)^
alter table GKLIENTS_ELVER_SUBSCRIPTION add constraint FK_GKLIENTS_ELVER_SUBSCRIPTION_RIZ_ID foreign key (RIZ_ID) references GKLIENTS_RIZ(ID)^
alter table GKLIENTS_ELVER_SUBSCRIPTION add constraint FK_GKLIENTS_ELVER_SUBSCRIPTION_TARIF_ID foreign key (TARIF_ID) references GKLIENTS_TARIF(ID)^
alter table GKLIENTS_ELVER_SUBSCRIPTION add constraint FK_GKLIENTS_ELVER_SUBSCRIPTION_ISSUE_START_ID foreign key (ISSUE_START_ID) references GKLIENTS_MAGAZINE_ISSUE(ID)^
alter table GKLIENTS_ELVER_SUBSCRIPTION add constraint FK_GKLIENTS_ELVER_SUBSCRIPTION_ISSUE_END_ID foreign key (ISSUE_END_ID) references GKLIENTS_MAGAZINE_ISSUE(ID)^
create unique index IDX_GKLIENTS_ELVER_SUBSCRIPTION_UNIQ_REGKEY on GKLIENTS_ELVER_SUBSCRIPTION (REGKEY) where DELETE_TS is null ^
create index IDX_GKLIENTS_ELVER_SUBSCRIPTION_TARIF on GKLIENTS_ELVER_SUBSCRIPTION (TARIF_ID)^
create index IDX_GKLIENTS_ELVER_SUBSCRIPTION_ISSUE_END on GKLIENTS_ELVER_SUBSCRIPTION (ISSUE_END_ID)^
create index IDX_GKLIENTS_ELVER_SUBSCRIPTION_CLIENT on GKLIENTS_ELVER_SUBSCRIPTION (CLIENT_ID)^
create index IDX_GKLIENTS_ELVER_SUBSCRIPTION_RIZ on GKLIENTS_ELVER_SUBSCRIPTION (RIZ_ID)^
create index IDX_GKLIENTS_ELVER_SUBSCRIPTION_ISSUE_START on GKLIENTS_ELVER_SUBSCRIPTION (ISSUE_START_ID)^
-- end GKLIENTS_ELVER_SUBSCRIPTION
-- begin GKLIENTS_CLIENTalter table GKLIENTS_CLIENT add constraint FK_GKLIENTS_CLIENT_ORIGIN foreign key (ORIGIN_ID) references gklients_ORIGIN(ID)^
create unique index IDX_GKLIENTS_CLIENT_UK_EMAIL on GKLIENTS_CLIENT (EMAIL) where DELETE_TS is null ^
create index IDX_GKLIENTS_CLIENT_ORIGIN on GKLIENTS_CLIENT (ORIGIN_ID)^
-- end GKLIENTS_CLIENT
-- begin GKLIENTS_RIZ_MUN_OBRAZ_LINKalter table GKLIENTS_RIZ_MUN_OBRAZ_LINK add constraint FK_GRMOL_RIZ foreign key (RIZ_ID) references gklients_RIZ (ID)^
alter table GKLIENTS_RIZ_MUN_OBRAZ_LINK add constraint FK_GRMOL_MUN_OBRAZ foreign key (MUN_OBRAZ_ID) references GKLIENTS_MUN_OBRAZ (ID)^
-- end GKLIENTS_RIZ_MUN_OBRAZ_LINK
-- begin GKLIENTS_RIZ_CONTRACT
alter table GKLIENTS_RIZ_CONTRACT add constraint FK_GKLIENTS_RIZ_CONTRACT_RIZ_ID foreign key (RIZ_ID) references GKLIENTS_RIZ(ID)^
create index IDX_GKLIENTS_RIZ_CONTRACT_RIZ on GKLIENTS_RIZ_CONTRACT (RIZ_ID)^
-- end GKLIENTS_RIZ_CONTRACT

-- begin GKLIENTS_TEST_MARK
alter table GKLIENTS_TEST_MARK add constraint FK_GKLIENTS_TEST_MARK_TEST_ID foreign key (TEST_ID) references GKLIENTS_TEST(ID)^
alter table GKLIENTS_TEST_MARK add constraint FK_GKLIENTS_TEST_MARK_EMAIL_ID foreign key (EMAIL_ID) references GKLIENTS_TEST_EMAIL(ID)^
create index IDX_GKLIENTS_TEST_MARK_EMAIL on GKLIENTS_TEST_MARK (EMAIL_ID)^
create index IDX_GKLIENTS_TEST_MARK_TEST on GKLIENTS_TEST_MARK (TEST_ID)^
-- end GKLIENTS_TEST_MARK
-- begin GKLIENTS_CLIENT_SERVICE
alter table GKLIENTS_CLIENT_SERVICE add constraint FK_GKLIENTS_CLIENT_SERVICE_CLIENT foreign key (CLIENT_ID) references GKLIENTS_CLIENT(ID)^
create index IDX_GKLIENTS_CLIENT_SERVICE_CLIENT on GKLIENTS_CLIENT_SERVICE (CLIENT_ID)^
-- end GKLIENTS_CLIENT_SERVICE
-- begin GKLIENTS_WEBSITE_QUEUE_FILTER
alter table GKLIENTS_WEBSITE_QUEUE_FILTER add constraint FK_GKLIENTS_WEBSITE_QUEUE_FILTER_WEBSITE_QUEUE_ITEM foreign key (WEBSITE_QUEUE_ITEM_ID) references GKLIENTS_WEBSTIE_QUEUE(ID)^
create index IDX_GKLIENTS_WEBSITE_QUEUE_FILTER_WEBSITE_QUEUE_ITEM on GKLIENTS_WEBSITE_QUEUE_FILTER (WEBSITE_QUEUE_ITEM_ID)^
-- end GKLIENTS_WEBSITE_QUEUE_FILTER
-- begin GKLIENTS_CLIENT_DISTRIBUTION_SETTINGS
alter table GKLIENTS_CLIENT_DISTRIBUTION_SETTINGS add constraint FK_GKLIENTS_CLIENT_DISTRIBUTION_SETTINGS_CLIENT foreign key (CLIENT_ID) references GKLIENTS_CLIENT(ID)^
-- end GKLIENTS_CLIENT_DISTRIBUTION_SETTINGS
-- begin GKLIENTS_DISTRIBUTION
alter table GKLIENTS_DISTRIBUTION add constraint FK_GKLIENTS_DISTRIBUTION_TEMPLATE foreign key (TEMPLATE_ID) references gklients_EMAIL_TEMPLATE(ID)^
create index IDX_GKLIENTS_DISTRIBUTION_TEMPLATE on GKLIENTS_DISTRIBUTION (TEMPLATE_ID)^
-- end GKLIENTS_DISTRIBUTION
-- begin GKLIENTS_DISTRIBUTION_SUBSCRIPTION
alter table GKLIENTS_DISTRIBUTION_SUBSCRIPTION add constraint FK_GKLIENTS_DISTRIBUTION_SUBSCRIPTION_DISTRIBUTION foreign key (DISTRIBUTION_ID) references GKLIENTS_DISTRIBUTION(ID)^
alter table GKLIENTS_DISTRIBUTION_SUBSCRIPTION add constraint FK_GKLIENTS_DISTRIBUTION_SUBSCRIPTION_CLIENT foreign key (CLIENT_ID) references GKLIENTS_CLIENT(ID)^
create index IDX_GKLIENTS_DISTRIBUTION_SUBSCRIPTION_DISTRIBUTION on GKLIENTS_DISTRIBUTION_SUBSCRIPTION (DISTRIBUTION_ID)^
create index IDX_GKLIENTS_DISTRIBUTION_SUBSCRIPTION_CLIENT on GKLIENTS_DISTRIBUTION_SUBSCRIPTION (CLIENT_ID)^
-- end GKLIENTS_DISTRIBUTION_SUBSCRIPTION

-- begin GKLIENTS_ONETIME_MAILING_CLIENT_LINK
alter table GKLIENTS_ONETIME_MAILING_CLIENT_LINK add constraint FK_GOMCL_ONETIME_MAILING foreign key (ONETIME_MAILING_ID) references GKLIENTS_ONETIME_MAILING(ID)^
alter table GKLIENTS_ONETIME_MAILING_CLIENT_LINK add constraint FK_GOMCL_CLIENT foreign key (CLIENT_ID) references GKLIENTS_CLIENT(ID)^
-- end GKLIENTS_ONETIME_MAILING_CLIENT_LINK
-- begin GKLIENTS_RIZ
alter table gklients_RIZ add constraint FK_GKLIENTS_RIZ_PODHOST foreign key (PODHOST_ID) references gklients_RIZ(ID)^
create index IDX_GKLIENTS_RIZ_PODHOST on gklients_RIZ (PODHOST_ID)^
-- end GKLIENTS_RIZ
-- begin GKLIENTS_ATTACHMENT
alter table GKLIENTS_ATTACHMENT add constraint FK_GKLIENTS_ATTACHMENT_FILE foreign key (FILE_ID) references SYS_FILE(ID)^
create index IDX_GKLIENTS_ATTACHMENT_FILE on GKLIENTS_ATTACHMENT (FILE_ID)^
-- end GKLIENTS_ATTACHMENT
-- begin GKLIENTS_EMAIL_TEMPLATE_ATTACHMENT_LINK
alter table GKLIENTS_EMAIL_TEMPLATE_ATTACHMENT_LINK add constraint FK_GETAL_ATTACHMENT foreign key (ATTACHMENT_ID) references GKLIENTS_ATTACHMENT(ID)^
alter table GKLIENTS_EMAIL_TEMPLATE_ATTACHMENT_LINK add constraint FK_GETAL_EMAIL_TEMPLATE foreign key (EMAIL_TEMPLATE_ID) references gklients_EMAIL_TEMPLATE(ID)^
-- end GKLIENTS_EMAIL_TEMPLATE_ATTACHMENT_LINK

-- begin GKLIENTS_DISTRIBUTION_ATTACHMENT_LINK
alter table GKLIENTS_DISTRIBUTION_ATTACHMENT_LINK add constraint FK_GDAL_ATTACHMENT foreign key (ATTACHMENT_ID) references GKLIENTS_ATTACHMENT(ID)^
alter table GKLIENTS_DISTRIBUTION_ATTACHMENT_LINK add constraint FK_GDAL_DISTRIBUTION foreign key (DISTRIBUTION_ID) references GKLIENTS_DISTRIBUTION(ID)^
-- end GKLIENTS_DISTRIBUTION_ATTACHMENT_LINK
-- begin GKLIENTS_ONETIME_MAILING_ATTACHMENT_LINK
alter table GKLIENTS_ONETIME_MAILING_ATTACHMENT_LINK add constraint FK_GOMAL_ATTACHMENT foreign key (ATTACHMENT_ID) references GKLIENTS_ATTACHMENT(ID)^
alter table GKLIENTS_ONETIME_MAILING_ATTACHMENT_LINK add constraint FK_GOMAL_ONETIME_MAILING foreign key (ONETIME_MAILING_ID) references GKLIENTS_ONETIME_MAILING(ID)^
-- end GKLIENTS_ONETIME_MAILING_ATTACHMENT_LINK

-- begin GKLIENTS_GK_NEWS_IMAGE
alter table GKLIENTS_GK_NEWS_IMAGE add constraint FK_GKLIENTS_GK_NEWS_IMAGE_GK_NEWS foreign key (GK_NEWS_ID) references GKLIENTS_GK_NEWS(ID)^
create index IDX_GKLIENTS_GK_NEWS_IMAGE_GK_NEWS on GKLIENTS_GK_NEWS_IMAGE (GK_NEWS_ID)^
-- end GKLIENTS_GK_NEWS_IMAGE
-- begin GKLIENTS_ONETIME_MAILING
alter table GKLIENTS_ONETIME_MAILING add constraint FK_GKLIENTS_ONETIME_MAILING_TEMPLATE foreign key (TEMPLATE_ID) references gklients_EMAIL_TEMPLATE(ID)^
create index IDX_GKLIENTS_ONETIME_MAILING_TEMPLATE on GKLIENTS_ONETIME_MAILING (TEMPLATE_ID)^
-- end GKLIENTS_ONETIME_MAILING
-- begin GKLIENTS_MAILING_STATISTICS
alter table GKLIENTS_MAILING_STATISTICS add constraint FK_GKLIENTS_MAILING_STATISTICS_ONETIME_MAILING foreign key (ONETIME_MAILING_ID) references GKLIENTS_ONETIME_MAILING(ID)^
create index IDX_GKLIENTS_MAILING_STATISTICS_ONETIME_MAILING on GKLIENTS_MAILING_STATISTICS (ONETIME_MAILING_ID)^
-- end GKLIENTS_MAILING_STATISTICS
-- begin GKLIENTS_FAILED_EMAILS
alter table GKLIENTS_FAILED_EMAILS add constraint FK_GKLIENTS_FAILED_EMAILS_CLIENT foreign key (CLIENT_ID) references GKLIENTS_CLIENT(ID)^
alter table GKLIENTS_FAILED_EMAILS add constraint FK_GKLIENTS_FAILED_EMAILS_ONETIME_MAILING foreign key (ONETIME_MAILING_ID) references GKLIENTS_ONETIME_MAILING(ID)^
alter table GKLIENTS_FAILED_EMAILS add constraint FK_GKLIENTS_FAILED_EMAILS_MAILING_STATISTICS foreign key (MAILING_STATISTICS_ID) references GKLIENTS_MAILING_STATISTICS(ID)^
create index IDX_GKLIENTS_FAILED_EMAILS_CLIENT on GKLIENTS_FAILED_EMAILS (CLIENT_ID)^
create index IDX_GKLIENTS_FAILED_EMAILS_ONETIME_MAILING on GKLIENTS_FAILED_EMAILS (ONETIME_MAILING_ID)^
create index IDX_GKLIENTS_FAILED_EMAILS_MAILING_STATISTICS on GKLIENTS_FAILED_EMAILS (MAILING_STATISTICS_ID)^
-- end GKLIENTS_FAILED_EMAILS
-- begin GKLIENTS_MAGAZINE_ISSUE
alter table gklients_MAGAZINE_ISSUE add constraint FK_GKLIENTS_MAGAZINE_ISSUE_MAGAZINE foreign key (MAGAZINE_ID) references gklients_MAGAZINE(ID)^
create index IDX_GKLIENTS_MAGAZINE_ISSUE_MAGAZINE on gklients_MAGAZINE_ISSUE (MAGAZINE_ID)^
-- end GKLIENTS_MAGAZINE_ISSUE
-- begin GKLIENTS_SCHEDULE
alter table gklients_SCHEDULE add constraint FK_GKLIENTS_SCHEDULE_MAGAZINE_ISSUE foreign key (MAGAZINE_ISSUE_ID) references gklients_MAGAZINE_ISSUE(ID)^
-- end GKLIENTS_SCHEDULE
